Feature/api call event
TheInteract/Artemis pull request #19
Opened 2017-03-08 06:20 UTC by chaoexit

2017-03-09 11:59 UTC, 0xchimz requested changes

2017-03-09 11:59 UTC, chinclubi commented on client/events/index.js
> +    callFetch(fetch, type, data, this)
- refactor code 
`callFetch.call(this, type, data)`

2017-03-09 11:59 UTC, chinclubi commented on client/util/fetch.js
> +let hasError = false
hasError in BrowserFetch is never used

2017-03-09 11:59 UTC, chinclubi commented on client/events/index.js
>  function callFetch (fetch, type, data) {
bind callFetch method for calling fetch function with this.fetch

2017-03-10 08:46 UTC, chaoexit commented
Modified as reviewed, please check @chinclubi

2017-03-10 10:06 UTC, 0xchimz approved these changes

2017-03-10 10:34 UTC, merged